### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by j0ach1mmall3** [j0ach1mmall3/TwitterScrapeAPI#1]
- [x] Quoted Tweets
- [x] Media in Tweets
- [x] Polls in Tweets
- [x] User cover image
